name: Extract ZIP File

on:
  push:
    branches:
      - main  # Runs when you push to the main branch
  workflow_dispatch:  # Allows manual execution

jobs:
  extract_zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install unzip utility
        run: sudo apt-get install unzip -y

      - name: Extract ZIP file
        run: unzip "push notification_042552.zip" -d extracted_files

      - name: List extracted contents
        run: ls -l extracted_files

      - name: Commit extracted files back to the repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add extracted_files/*
          git commit -m "Extracted ZIP file contents"
          git push
